version: '3'
services:
  database:
    container_name: database
    build: ./docker/postgresql/.
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/database_data:/var/lib/postgresql/data
  
  backend:
    container_name: backend
    build: ./app/back-end/.
    ports:
      - 3001:3000
    tty: true
    depends_on:
      - database
    volumes:
      - ./app/back-end/:/var/www/app

    